rrr_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  test_controller:
    type: gazebo_clik/Gazebo_Clik
    joints: [jnt_1,jnt_2,jnt_3]
    urdf: /home/jacopo/ROS_WS/src/first_rrr/urdf/model.urdf
    first_link: base_link
    ee_link: end_effector_link
    gazebo: 1   
  joint1_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: jnt_1
    pid: {p: 100.0, i: 0.0, d: 0.0}
  joint2_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: jnt_2
    pid: {p: 100.0, i: 0.0, d: 0.0}
  joint3_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: jnt_3
    pid: {p: 100.0, i: 0.0, d: 0.0}
